<?php

/**
 * Implements hook_theme().
 */
function babylonjs_viewer_theme($existing, $type, $theme, $path) {
  return [
    'babylonjs_formatter' => [
      'variables' => [
        'file_url' => NULL,
      ],
      'template' => 'babylonjs-formatter',
      'render element' => 'element', // Añade esta línea
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function babylonjs_viewer_preprocess_babylonjs_formatter(&$variables) {
  // Añade la librería a través del preprocesador
  $variables['#attached']['library'][] = 'babylonjs_viewer/babylon_viewer';
  
  // Pasa la variable file_url a Twig
  $variables['content']['#attributes']['file_url'] = $variables['file_url'];
}